# Generated by Django 4.0 on 2025-08-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='publish_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
