# Generated by Django 4.0 on 2025-08-18 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0005_new_view_count_alter_comment_new_alter_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='view_count',
        ),
    ]
