# Generated by Django 5.2.5 on 2025-08-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0006_remove_new_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='body_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='body_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='body_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
